<?php
/**
 * Plugin Name: CJR3-Code
 * Description: Shortcode for displaying code more beautifully, with line numbers.
 * 
 * Usage:
 * 
 * [code]
 * var something = 1;
 * var somethingElse = 2;
 * [/code]
 * 
 * Output:
 * 1 : var something = 1;
 * 2 : var somethingElse = 2;
 * 
 * (Line numbers are generated by CSS.)
 */

/**
 * Initializes the plugin
 */
function cjr3_code_init() {
    //only on the admin side
    if(!is_admin()) {
        add_shortcode('code', 'cjr3_code_shortcode');
        add_action('wp_enqueue_scripts', 'cjr3_code_scripts');
    }
}

/**
 * Adds the default styles.
 */
function cjr3_code_scripts() {
    wp_enqueue_style('cjr3-code', plugin_dir_url(__FILE__) . "/cjr3.code.css");
}

/**
 * Handles the shortcode request for 'code'
 * @param array|string $atts
 * @param string $content
 * @param string $tag
 * @return string
 */
function cjr3_code_shortcode($atts, $content = null, $tag = null) {
    if(is_array($atts))
        $atts = array_change_key_case($atts, CASE_LOWER);
    $values = shortcode_atts(array(
        'language' => ""
    ), $atts, $tag);
    
    switch($values['language']) {
        default :
            return cjr3_code_general( $content );
            break;
    }
}

/**
 * Gets the opening HTML tag.
 * @param string $name CSS-Name
 * @return string
 */
function cjr3_code_start($name = "cjr3-code-simple") {
    return "<div class=\"cjr3-code " . $name . "\">";
}

/**
 * Converts the content to a series of spans for line numbering.
 * @param string $content
 * @return string
 */
function cjr3_code_content($content) {
    $parts = explode("\n",str_ireplace("\r","",strip_tags($content)));
    $html = "";
    $i = 0;
    foreach($parts as $part) {
        if(!empty($part))
            $html .= "<span>" . $part . "</span>";
        else if( $i > 0 && ($i+1) < count($parts))
            $html .= "<span>&nbsp;</span>";
        $i++;
    }
    return $html;
}

/**
 * General code formating.
 * @param string $content
 * @return string
 */
function cjr3_code_general( $content ) {
    if(empty($content))
        return "";
    return cjr3_code_start() . cjr3_code_content($content) . "</div>";
}


//Wordpress Hook
add_action('plugins_loaded', 'cjr3_code_init');